apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: danielburns-info-tls
spec:
  secretName: danielburns-info
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: danielburns.info
  dnsNames:
    - danielburns.info
    - www.danielburns.info
  acme:
    config:
      - http01 
          ingressClass: nginx
        domains:
          - danielburns.info
          - www.danielburns.info

