apiVersion: cert-manager.io/1valpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec: 
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: 'danielburnstech@gmail.com'
    privateKeySecretRef:
      name: letsencrypt-prod
    http01: {}
